baseURL = "https://bafto.dev/"
languageCode = "en"
defaultContentLanguage = "en"

title = "bafto"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Hendrik Ziegler"
  headline = "bafto"
  # image = "img/transparent.png"  # path relative to static directory

  links = [
    { github = "https://github.com/bafto" },
	{ ddp = { href = "https://ddp.im/", text = "DDP", icon = "ddp-logo" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

